#!/bin/bash

SITE=$(basename $1)

if [ ! -d "/var/www/ezproxy/sites-available/$SITE" ]
then
  echo "No such site $SITE"
  exit 1
fi

ln -s "/var/www/ezproxy/sites-available/$SITE" "/var/www/ezproxy/sites-enabled/"

